Fix nil.permit error in PublicationsController
After upgrade, got:
>NoMethodError: undefined method `permit' for nil:NilClass
    app/controllers/publications_controller.rb:125:in `whitelisted_publication_params'

In Rails 5.0, `params` returns an object instead of a HashWithIndifferentAccess.
Thus `params[:x]` returns `nil` instead of `{ }` when params[:x] is empty.

This happens whenever publications create or update is called with empty params[:publications]. There are two tests which do this.

My fix was to make `whitelisted_publication_params' return `{ }` whenever params[:publications] is empty.

- Also used %i literal for list of symbols.