Put printf args on separate lines for debugging
Log for [Travis Build #2039](https://travis-ci.org/MushroomObserver/mushroom-observer/builds/567213424?utm_source=github_status&utm_medium=notification) says:
```
724 /home/travis/build/MushroomObserver/mushroom-observer/script/monitor_top:46:in `block in <main>': undefined method `/' for nil:NilClass (NoMethodError)
```
But there are 2 calls to `\` in monitor_top:46. So put them on separate lines so that Travis will id the (first) one that's called on nil.