Get entire test suite to green (except Skipped, unwritten methods).  Error was:
ERROR["test_altering_types_shown_by_rss_log_index", ...
 test_altering_types_shown_by_rss_log_index#ObserverControllerTest
NoMethodError: undefined method `empty?' for false:FalseClass
      app/classes/query/rss_log.rb:37:in `add_rss_log_type_condition'

  * `types &= RssLog.all_types` was always false because **variable** `types` was undefined,
`empty?` is not a method of FalseClass.
  * Therefore define _variable_ `types`.