Write test of Observation.without_sequence
Test is red:
```ruby
ERROR ObservationTest#test_scope_without_sequence (0.83s)
Minitest::UnexpectedError:         NoMethodError: undefined method `missing'
...
           app/models/observation.rb:385:in `block in <class:Observation>'
            test/models/observation_test.rb:1207:in `test_scope_without_sequence'
```