Fix test_edit_redirect reversion Error in LogItemPresenter
Another error caused by the merger of bootstrap4 into this branch:

```ruby
ERROR["test_edit_redirect", #<Minitest::Reporters::Suite:0x0000560664e60ff8 @name="CollectionNumbersControllerTest">, 81.83446720501524]
 test_edit_redirect#CollectionNumbersControllerTest (81.83s)
Minitest::UnexpectedError:         ActionView::Template::Error: undefined local variable or method `observation' for #<LogItemPresenter:0x0000560662a86740>
            app/presenters/log_item_presenter.rb:51:in `rss_log_to_presenter'
            app/presenters/log_item_presenter.rb:23:in `initialize'
            app/views/shared/_log_item.html.erb:4:in `new'
            app/views/shared/_log_item.html.erb:4:in `_app_views_shared__log_item_html_erb__351505723885060106_47292733659160'
            app/views/collection_numbers/edit.html.erb:24:in `block in _app_views_collection_numbers_edit_html_erb___3469276395678113819_47292725708440'
            app/views/collection_numbers/edit.html.erb:23:in `_app_views_collection_numbers_edit_html_erb___3469276395678113819_47292725708440'
            app/controllers/application_controller.rb:226:in `catch_errors_and_log_request_stats'
            test/functional_test_case.rb:26:in `get'
            test/controllers/collection_numbers_controller_test.rb:270:in `test_edit_redirect'
```

Unfortunately, this exposes a new error:
```ruby
ERROR["test_edit_redirect", #<Minitest::Reporters::Suite:0x00005567f089da70 @name="CollectionNumbersControllerTest">, 9.877498387999367]
 test_edit_redirect#CollectionNumbersControllerTest (9.88s)
Minitest::UnexpectedError:         ActionView::Template::Error: undefined local variable or method `img_proportion' for #<#<Class:0x00005567efd3aa98>:0x00005567efd3f138>
            app/views/images/_image_thumbnail.html.erb:22:in `_app_views_images__image_thumbnail_html_erb___1821117997399467897_46952451677600'
            app/helpers/thumbnail_helper.rb:85:in `thumbnail'
            app/presenters/log_item_presenter.rb:67:in `rss_log_to_presenter'
            app/presenters/log_item_presenter.rb:24:in `initialize'
            app/views/shared/_log_item.html.erb:4:in `new'
            app/views/shared/_log_item.html.erb:4:in `_app_views_shared__log_item_html_erb__789096988942984449_46952450480540'
            app/views/collection_numbers/edit.html.erb:24:in `block in _app_views_collection_numbers_edit_html_erb___2114957099274479852_46952447307520'
            app/views/collection_numbers/edit.html.erb:23:in `_app_views_collection_numbers_edit_html_erb___2114957099274479852_46952447307520'
            app/controllers/application_controller.rb:226:in `catch_errors_and_log_request_stats'
            test/functional_test_case.rb:26:in `get'
            test/controllers/collection_numbers_controller_test.rb:270:in `test_edit_redirect'
```