Fix ExpertTest#test_sequences
Use `obs_id` query param instead of `id` route param
Fixes
```ruby
ERROR ExpertTest#test_sequences (5.45s)
Minitest::UnexpectedError:         ActionView::Template::Error: undefined method `show_link_args' for nil:NilClass
            app/views/sequences/new.html.erb:5
            app/controllers/application_controller.rb:236:in `catch_errors_and_log_request_stats'
            test/session_extensions.rb:91:in `get'
            test/session_extensions.rb:70:in `process_with_error_checking'
            test/session_extensions.rb:93:in `get'
            test/session_extensions.rb:296:in `block (2 levels) in try_finding_matching_anchor'
            test/session_extensions.rb:292:in `block in try_finding_matching_anchor'
            test/session_extensions.rb:291:in `try_finding_matching_anchor'
            test/session_extensions.rb:281:in `click_mo_link'
```