Rails/RakeEnvironment lang.rake
Added `:environment` as a dependency to 4 tasks.
I don't understand the tasks.
But without this dependency, I got
```ruby
joe@iMac mushroom-observer % rake lang:login_admin
rake aborted!
NameError: uninitialized constant User (NameError)

    User.current = User.find(0)
    ^^^^
/Users/joe/mushroom-observer/lib/tasks/lang.rake:91:in `block (2 levels) in <top (required)>'
Tasks: TOP => lang:login_admin
(See full trace by running task with --trace)
```