Fix error introduced in prior commit
>Minitest::UnexpectedError:         NameError: undefined local variable or method `params'
for #<LocationControllerTest:0x00007fa358eb1f10 @NAME="test_location_bounding_box"