Fix Error caused by wrong merger choice in prior commit
```
ERROR["test_refresh_classification_caches", #<Minitest::Reporters::Suite:0x000055e86c62c7f8 @name="NameTest">, 24.268938643988804]
 test_refresh_classification_caches#NameTest (24.27s)
Minitest::UnexpectedError:         NameError: undefined local variable or method `nd' for #<Class:0x000055e864de3ee0>
            app/models/name/taxonomy.rb:557:in `refresh_classification_caches'
            test/models/name_test.rb:3037:in `test_refresh_classification_caches'
```
I should have accepted both branches, rather than just master.
Fixed by adding changes from this branch