`bundle exec rake` rather than plain old `rake`
Trying to fix this error from GitHub Actions:
```
Run rake db:schema:load
rake aborted!
Gem::LoadError: You have already activated rake 12.3.3, but your Gemfile requires rake 13.0.3. Prepending `bundle exec` to your command may solve this.
/home/runner/work/mushroom-observer/mushroom-observer/config/boot.rb:6:in `<top (required)>'
/home/runner/work/mushroom-observer/mushroom-observer/config/application.rb:3:in `<top (required)>'
/home/runner/work/mushroom-observer/mushroom-observer/Rakefile:6:in `<top (required)>'
(See full trace by running task with --trace)
Error: Process completed with exit code 1.
```