Try to fix CI Error on PR run
This Error below occurs only during CI, only during the PR run (and not in the Push run).
The fix was suggested by ChatGPT
```
Run bundle exec rake db:schema:load
  bundle exec rake db:schema:load
  bundle exec rake db:fixtures:load
  shell: /usr/bin/bash -e {0}
rake aborted!
NoMethodError: private method `t' called for an instance of Symbol (NoMethodError)

              message: :validate_name_author_characters.t
                                                       ^^
/home/runner/work/mushroom-observer/mushroom-observer/app/models/name.rb:429:in `<class:Name>'
/home/runner/work/mushroom-observer/mushroom-observer/app/models/name.rb:331:in `<top (required)>'
/home/runner/work/mushroom-observer/mushroom-observer/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:26:in `require'
/home/runner/work/mushroom-observer/mushroom-observer/app/models/comment.rb:115:in `<class:Comment>'
/home/runner/work/mushroom-observer/mushroom-observer/app/models/comment.rb:107:in `<top (required)>'
/home/runner/work/mushroom-observer/mushroom-observer/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:26:in `require'
/home/runner/work/mushroom-observer/mushroom-observer/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/inflector/methods.rb:290:in `const_get'
/home/runner/work/mushroom-observer/mushroom-observer/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/inflector/methods.rb:290:in `constantize'
/home/runner/work/mushroom-observer/mushroom-observer/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/inflector/methods.rb:316:in `safe_constantize'
/home/runner/work/mushroom-observer/mushroom-observer/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/core_ext/string/inflections.rb:87:in `safe_constantize'
/home/runner/work/mushroom-observer/mushroom-observer/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2.1/lib/active_record/fixtures.rb:803:in `default_fixture_model_class'
/home/runner/work/mushroom-observer/mushroom-observer/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2.1/lib/active_record/fixtures.rb:793:in `block (2 levels) in read_fixture_files'
/home/runner/work/mushroom-observer/mushroom-observer/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2.1/lib/active_record/fixture_set/file.rb:16:in `open'
/home/runner/work/mushroom-observer/mushroom-observer/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2.1/lib/active_record/fixtures.rb:791:in `block in read_fixture_files'
/home/runner/work/mushroom-observer/mushroom-observer/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2.1/lib/active_record/fixtures.rb:790:in `each'
/home/runner/work/mushroom-observer/mushroom-observer/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2.1/lib/active_record/fixtures.rb:790:in `each_with_object'
/home/runner/work/mushroom-observer/mushroom-observer/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2.1/lib/active_record/fixtures.rb:790:in `read_fixture_files'
/home/runner/work/mushroom-observer/mushroom-observer/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2.1/lib/active_record/fixtures.rb:721:in `initialize'
/home/runner/work/mushroom-observer/mushroom-observer/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2.1/lib/active_record/fixtures.rb:653:in `new'
/home/runner/work/mushroom-observer/mushroom-observer/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2.1/lib/active_record/fixtures.rb:653:in `block in read_and_insert'
/home/runner/work/mushroom-observer/mushroom-observer/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2.1/lib/active_record/fixtures.rb:651:in `map'
/home/runner/work/mushroom-observer/mushroom-observer/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2.1/lib/active_record/fixtures.rb:651:in `read_and_insert'
/home/runner/work/mushroom-observer/mushroom-observer/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2.1/lib/active_record/fixtures.rb:607:in `create_fixtures'
/home/runner/work/mushroom-observer/mushroom-observer/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2.1/lib/active_record/railties/databases.rake:434:in `block (3 levels) in <top (required)>'
/home/runner/work/mushroom-observer/mushroom-observer/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/opt/hostedtoolcache/Ruby/3.3.6/x64/bin/bundle:25:in `load'
/opt/hostedtoolcache/Ruby/3.3.6/x64/bin/bundle:25:in `<main>'
Tasks: TOP => db:fixtures:load
```