On submit, leave field values == "" , instead of setting to nil * fixes following error ``` CuratorTest#test_herbarium_create: NoMethodError: undefined method `empty?' for nil:NilClass     app/controllers/herbarium_controller.rb:139:in `calc_herbarium_redirect'     app/controllers/herbarium_controller.rb:121:in `build_herbarium'     app/controllers/herbarium_controller.rb:91:in `create_herbarium'     app/controllers/application_controller.rb:195:in `catch_errors'     test/session_extensions.rb:69:in `process_with_error_checking'     test/session_extensions.rb:97:in `post'     test/session_form_extensions.rb:376:in `submit'     test/integration/curator_test.rb:89:in `block in test_herbarium_create'     test/session_extensions.rb:186:in `block in open_form'     test/session_extensions.rb:179:in `open_form'     test/integration/curator_test.rb:82:in `test_herbarium_create' ```