Add test exposing bug in merging notes
Exposes this bug when mergin a Name with notes into a Name with nil notes:
```ruby
INFO -- : Started PATCH "/names/5013" for 24.147.85.215 at 2025-03-26 11:43:45 +0000
INFO -- : Processing by NamesController#update as HTML
INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "commit"=>"Save Edits", "name"=>{"locked"=>"0", "icn_id"=>"193923", "rank"=>"Species", "deprecated"=>"true", "text_name"=>"Fistulina hepatica", "author"=>"(Schaeff.) With.", "citation"=>"Syst. arr. Brit. pl., Edn 4 (London) 4: 302 (1801)", "misspelling"=>"0", "correct_spelling"=>"", "name_id"=>"", "notes"=>"Gilbertson and Ryvarden.  1986.  North American Polypores Vol I.\r\n\r\n<br/>There is some lack of clarity around the correct author citation.  My understanding is that the use of ':' in author citations is optional as of the Toyoko revision of the ICBN.  From what I can reconstruct looking at Index Fungorum and other sites, Schaeffer original published this species as __Boletus hepatica__.  Withering transferred it to __Fistulina__ which was created by Bulliard.  However, all of this happened before the publication of __Systema Mycologicum__, but apparently Fries acknowledged this previous work in his san
 ctioning work.  Based on all that I believe the correct author reference is __Fistulina hepatica__ (Schaeff.) With.  This is what Index Fungorum lists for the type species for __Fistulina__ and is the citation used on MykoWeb, so I'm making that the approved name."}, "id"=>"5013"}
WARN -- : user=1 robot=N ip=24.147.85.215
INFO -- : Completed 500 Internal Server Error in 6509ms (ActiveRecord: 6475.0ms (34 queries, 2 cached) | GC: 2.4ms)
E, [2025-03-26T11:43:51.733269 #1377789] ERROR -- :
NoMethodError (undefined method `+' for nil):

app/models/name/merge.rb:127:in `move_taxonomy_attributes'
app/models/name/merge.rb:38:in `merge'
app/controllers/names_controller.rb:623:in `perform_merge_names'
app/controllers/names_controller.rb:596:in `merge_names'
app/controllers/names_controller.rb:408:in `update_name'
app/controllers/names_controller.rb:311:in `update'
app/controllers/application_controller.rb:215:in `catch_errors_and_log_request_stats'
```