Revert `Rails.root.join` in email.rake
Fixes error:
>rake aborted!
TypeError: no implicit conversion of Pathname into String
/usr/local/rvm/gems/ruby-3.1.2/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
/usr/local/rvm/gems/ruby-3.1.2/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
/var/web/mo/lib/tasks/email.rake:14:in `block (2 levels) in <top (required)>'
Tasks: TOP => email:send
(See full trace by running task with --trace)