Compensate for new behavior of CONTENT_TYPE
Various API POST tests Error like this:
>  8) Error:
ApiControllerTest#test_post_maximal_observation:
ActionView::Template::Error: undefined method `paginate_ids' for nil:NilClass
    app/classes/api/results.rb:68:in `result_ids'
    app/views/api/results.xml.builder:17:in `block in _app_views_api_results_xml_builder__3758528338010860035_86656420'
    app/views/api/results.xml.builder:2:in `_app_views_api_results_xml_builder__3758528338010860035_86656420'
    app/controllers/api_controller.rb:144:in `do_render_xml'
    app/controllers/api_controller.rb:138:in `block (2 levels) in do_render'
    app/controllers/api_controller.rb:137:in `do_render'
    app/controllers/api_controller.rb:131:in `rescue in render_api_results'
    app/controllers/api_controller.rb:125:in `render_api_results'
    app/controllers/api_controller.rb:82:in `rest_query'
    app/controllers/api_controller.rb:48:in `observations'
    app/controllers/application_controller.rb:208:in `catch_errors'
    test/functional_test_case.rb:30:in `post'
    test/controllers/api_controller_test.rb:112:in `test_post_maximal_observation'

The underlying cause is that in Rails 5.x request.headers["CONTENT_TYPE"] == "application/x-www-form-urlencoded".
This made upload_type return "application/x-www-form-urlencoded" instead of "";
which makes MO think there is something_to_post?;
which sets args[:upload];
which is an unexpected parameter;
 which causes an UnexpectedParameter error (which also is screwed up because it initializes incorrectly).

My fix was to also require that there be some upload_data.

Works for test environment. Seems logical for dev and production, but is it actually right?