Update obsolete cop names in RuboCop configuration
Update cop names and namespaces per messages from RuboCop:
>.rubocop_todo.yml: Metrics/LineLength has the wrong namespace - should be Layout
Error: The `Lint/HandleExceptions` cop has been renamed to `Lint/SuppressedException`.
(obsolete configuration found in .rubocop_todo.yml, please update it)
The `Lint/UnneededCopDisableDirective` cop has been renamed to `Lint/RedundantCopDisableDirective`.
(obsolete configuration found in .rubocop_todo.yml, please update it)
>
.rubocop_todo.yml: Metrics/LineLength has the wrong namespace - should be Layout
Error: The `Layout/AlignHash` cop has been renamed to `Layout/HashAlignment`.
(obsolete configuration found in .rubocop.yml, please update it)