Fix Errors caused by calling Species on Name
Revert code to what it was before `Name.Species`

Sample error:
```ruby
ERROR["test_checklist_for_site", "ChecklistTest", 2.172972377997212]
 test_checklist_for_site#ChecklistTest (2.17s)
NoMethodError:         NoMethodError: undefined method `Species' for #<Class:0x00000002311260>
            test/models/checklist_test.rb:34:in `test_checklist_for_site'
```

HOW DID `Name.Species` EVER PASS? It's been in master a long time.